=== InfinniPlatform/InfinniPlatform/Files/Schema/appConfig.json
{
  "id": "https://raw.githubusercontent.com/InfinniPlatform/InfinniPlatform/master/Files/Schema/appConfig.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "appConfig",
  "description": "InfinniPlatform application configuration.",
  "type": "object",
  "properties": {
    "app": {
      "description": "Настройки приложения.",
      "$ref": "https://raw.githubusercontent.com/InfinniPlatform/InfinniPlatform/master/Files/Schema/app.json"
    },
    "mongodbDocumentStorage": {
      "description": "Настройки хранилища документов MongoDB.",
      "$ref": "https://raw.githubusercontent.com/InfinniPlatform/InfinniPlatform/master/Files/Schema/mongodbDocumentStorage.json"
    },
    "fileSystemBlobStorage": {
      "description": "Настройки хранилища BLOB в файловой системе.",
      "$ref": "https://raw.githubusercontent.com/InfinniPlatform/InfinniPlatform/master/Files/Schema/fileSystemBlobStorage.json"
    },
    "rabbitmqMessageQueue": {
      "description": "Настройки очереди сообщений на основе RabbitMQ.",
      "$ref": "https://raw.githubusercontent.com/InfinniPlatform/InfinniPlatform/master/Files/Schema/rabbitmqMessageQueue.json"
    },
    "redisSharedCache": {
      "description": "Настройки распределенного кэша на основе Redis.",
      "$ref": "https://raw.githubusercontent.com/InfinniPlatform/InfinniPlatform/master/Files/Schema/redisSharedCache.json"
    },
    "auth": {
      "description": "Настройки внутреннего провайдера аутентификации.",
      "$ref": "https://raw.githubusercontent.com/InfinniPlatform/InfinniPlatform/master/Files/Schema/auth.json"
    },
    "quartzScheduler": {
      "description": "Настройки планировщика заданий Quartz.",
      "$ref": "https://raw.githubusercontent.com/InfinniPlatform/InfinniPlatform/master/Files/Schema/quartzScheduler.json"
    },
    "printView": {
      "description": "Настройки печатных представлений.",
      "$ref": "https://raw.githubusercontent.com/InfinniPlatform/InfinniPlatform/master/Files/Schema/printView.json"
    }
  }
}

=== InfinniPlatform/InfinniPlatform/InfinniPlatform.SandboxApp/AppConfig.json
{
  "$schema": "https://raw.githubusercontent.com/InfinniPlatform/InfinniPlatform/master/Files/Config/Schema/appConfig.json",
  "app": {
    "AppName": "InfinniPlatform",
    "AppInstance": "",
    "StaticFilesMapping": {
      "/": "wwwroot"
    }
  },
  "mongodbDocumentStorage": {
    "ConnectionString": "mongodb://localhost:27017"
  },
  "fileSystemBlobStorage": {
    "BaseDirectory": "BlobStorage"
  },
  "rabbitmqMessageQueue": {
    "HostName": "localhost",
    "Port": 5672,
    "UserName": "guest",
    "Password": "guest",
    "ManagementApiPort": 15672,
    "PrefetchCount": 1,
    "MaxConcurrentThreads": 200,
    "ReconnectTimeout": 5,
    "MaxReconnectRetries": 10
  },
  "redisSharedCache": {
    "Host": "localhost",
    "Port": 6379,
    "Database": 0,
    "Password": "",
    "ReadBufferSize": 512,
    "WriteBufferSize": 512,
    "ConnectionTimeout": 1000,
    "MaxReconnectRetries": 10,
    "PoolSize": 0
  },
  "auth": {
    "UserCacheTimeout": 30,
    "LoginPath": "/",
    "LogoutPath": "/"
  },
  "quartzScheduler": {
    "ExpireHistoryAfter": 30
  },
  "printView": {
    "TempDirectory": "",
    "WkHtmlToPdfPath": "",
    "WkHtmlToPdfArguments": ""
  }
}
